### ISSUE TITLE
What is the semantic of "clip::lock"?

### ISSUE THREAD

**Issue by Azure-Vani** [dacap/clip#6]
Does the clip::lock freeze the clipboard so that **other** process can not modify the content until clip::lock is destructed? Or it just is the util to manipulate clipboard?

**Comment by dacap** [comment]
Hi @Azure-Vani, yeah, that should be the expected behavior. Platforms like Windows or macOS provide a way to lock the clipboard temporarily to check its format and then retrieve the data in that format (this must be an atomic operation in a lock/unlock block).

Some of our examples are not 100% correct, like [this](https://github.com/dacap/clip/blob/master/examples/paste.cpp#L8) (they are written without locks just for simplicity):

```
  if (clip::has(clip::text_format())) {
    std::string value;
    clip::get_text(value);

    std::cout << "Clipboard content is '" << value << "'\n";
  }
 ```

In this case, as we don't lock the clipboard between the `clip::has(clip::text_format())` and `clip::get_text()` call, it might happen that `get_text()` fails because in the middle other application changes the clipboard content.

**Comment by Azure-Vani** [comment]
Cool! I've forked it and try to provide Linux clipboard support based on X11.  :)

**Comment by dacap** [comment]
@Azure-Vani it would be great! any kind of help you need, please ask
