### ISSUE TITLE
How to compile with g++

### ISSUE THREAD

**Issue by imexhausted** [dacap/clip#68]
I tried to compile example from README using command:
```g++ ./main.cpp ./clip/clip.cpp ./clip/clip_none.cpp -o clip```

Binary has been compiled without errors. 
Running it also doesn't give any errors.
But for some reason ```clip::set_text()``` doesn't modify clipboard.
Also ```clip::get_text()``` doesn't read text from clipboard. I guess it's because I'm doing everything in wrong way.

Can't figure out what to do with CMakeLists.txt because usually I use MAKEFILE and do everything via command line. 

If someone can explain how to install library step by step that would be really nice :)

Cant understand "How to use it", what do I do with CMakeLists.

Thanks in advance 

UPD: 
In my case this command worked:
```g++ ./main.cpp ./clip/clip.cpp ./clip/clip_x11.cpp ./clip/image.cpp -o main -lxcb -lxcb-randr -lpthread -I. -DCLIP_ENABLE_IMAGE=1 -DHAVE_XCB_XLIB_H```
Order is important. Also anyone with same problem also should install ```xcb``` ```xcb-randr``` and ```pthreads```
You can do this by running ```sudo apt install libxcb-randr0-dev libxcb1-dev xcb libpthread-stubs0-dev``` 
*if you're using Debian based distro ofc.*

**Comment by dacap** [comment]
Hi @imexhausted, the library is not working as expected because you've compile the "none" clipboard, which is just an internal implementation when nothing else is available (Windows, macOS, or X11).

If you are on Linux, from the command line you could try to compile an example this way:

    g++ ./examples/copy.cpp -I. -DCLIP_ENABLE_IMAGE=1 -DHAVE_XCB_XLIB_H -lxcb -lpthread ./clip_x11.cpp ./image.cpp

For cmake projects, you need to follow some instructions like this:

  $ mkdir build
  $ cd build
  build$ cmake -B . -S /path-of/clip-repo -G "Unix Makefiles"
  build$ make

This will compile all examples by default inside the `build/examples` directory.

**Comment by imexhausted** [comment]
I've managed to compile it. See UPD section in first message. Thanks @dacap
